INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (1, 'Amazing song!', 20190627, 5, 2);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (2, 'It''s my favourite one!', 20190630, 5, 5);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (3, 'Best one, ever!', 20190710, 5, 3);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (4, 'I could listen to it all day!', 20190711, 5, 1);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (5, 'Not bad for dancing.', 20190704, 4, 6);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (6, 'So beautiful!', 20190721, 5, 8);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (7, 'It''s worth paying attention to the lyrics, too.', 20190705, 5, 7);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (8, 'My favourite band!', 20190717, 5, 5);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (9, 'This song is spine-chilling and wonderful!', 20190626, 5, 1);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (10, 'Awesome!', 20190624, 5, 2);

INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (11, 'It has an incredible rhythm!', 20190724, 5, 3);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (12, 'I can''t help whistling it all day...', 20190719, 5, 2);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (13, 'Great music!', 20190723, 5, 4);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (14, 'A good song, but Imagine Dragons has better ones!', 20190620, 4, 4);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (15, 'Artistic video, a bit strange...', 20190618, 4, 6);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (16, 'So deeply emotional!', 20190707, 5, 1);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (17, 'Really scary video!', 20190704, 4, 2);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (18, 'What a pity they can''t make more music together!', 20190719, 5, 1);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (19, 'A powerful song!', 20190710, 5, 3);
INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (20, 'Absolutely fantastic!', 20190712, 5, 4);

INSERT INTO RECOMMENDATION (ID, COMMENT, CREATION_TIME, RATING, VIDEO_ID)
VALUES (21, 'A true masterpiece!', 20190716, 5, 2);